### ISSUE TITLE
Improved error handling forAssume Role with Web Identity command

### ISSUE THREAD

**Issue by adamdmharvey** [CircleCI-Public/aws-cli-orb#106]
This is to suggest some improved error handling for the Assume Role with Web Identity Command:

https://circleci.com/developer/orbs/orb/circleci/aws-cli#commands-assume-role-with-web-identity

Specifically, that it **should fail** if it cannot successfully assume the role.

When using this command at first, it worked. We intentionally changed our target role to assume to change the string matching to thus invalidate the call.  However, the step from the orb reports green in the UI, even though inside the step it is clear the assume role was not successful:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/33203301/166292443-3c376416-2388-481f-a573-dc1a90777493.png">

However, if you open the "Generate short-lived AWS keys" step, it is the one which actually failed:

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/33203301/166292522-89094b1e-8184-4829-9c2a-c8490dd68bd3.png">

It would make more sense (we believe) to have this exact step fail for those troubleshooting to identify the actually source of the error, as opposed to our subsequent custom steps performing actual AWS work reporting that we haven't yet logged into AWS successfully.

**Comment by brivu** [comment]
Hey @adamdmharvey, 

Thanks for letting us know. I think this is a bug with the `AWS CLI` specifically. 

In the script below, I am purposely setting `PARAM_ROLE_SESSION_NAME` to a blank space so that the command fails. I am also echoing `$?` to check the status code of the command. 
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/64455338/166323981-f0e75f11-6dc7-4294-bcae-bdcd8dd37d7a.png">

As you can see below, the script obviously fails judging from the error message, yet the exit code is still `0`.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/64455338/166323867-4701fc8b-de5b-4fde-9d2b-bfb2c332e43d.png">

The only thing I can think of is adding our own validation checking to see if the `PARAM_ROLE_SESSION_NAME` is empty along with the `AWS_SESSION_TOKEN`. The thought is if assuming the role is successful, a session token is generated. If there is no session token, then the command failed.

My question is in your specific case, is a session token generated? If there is, can you think of any other way to handle the error?

Let me know and thanks for catching this! 

Best, 
Brian

**Comment by brivu** [comment]
Hey @adamdmharvey, 

I did some digging and I ended validating the command by using `${PIPESTATUS[0]}`. It'll cause the command to fail with the appropriate errors and exit codes from `AWS` 

Best, 
Brian

**Comment by adamdmharvey** [comment]
Thanks, @brivu . My speculation was it was not an error with the CLI, and unrelated to the session name, but with the wrapping of the CLI call into the read statement, such that any error in the CLI would effectively be "trapped" by the outer command, and even if the result was invalid environment variables, we'd get an exit 0.

Just running a raw assume role which fails, it definitely returns an exit code 254:

```shell
$ aws sts assume-role-with-web-identity \
            --role-arn 'arn:aws:iam::1234567890:role/fake-role' \
            --role-session-name 'my-session' \
            --web-identity-token 'fake-token' \
            --duration-seconds 3600 \
            --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
            --output text

An error occurred (InvalidIdentityToken) when calling the AssumeRoleWithWebIdentity operation: The ID Token provided is not a valid JWT. (You may see this error if you sent an Access Token)

$ echo $?
254
```

Excited about your change; thanks for the quick turnaround. Happy to give it a shot on my end!!

**Comment by adamdmharvey** [comment]
My team and I just tested this orb fix and can confirm a user who is not authorized to assume the role in AWS, when triggering the pipeline now successfully gets an error message on this step.  So for now, the fix addresses my issue; thanks Brian!

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/33203301/166507396-1980ad3c-ad0a-4011-9ae5-8e30d2729d90.png">
