### ISSUE TITLE
setup not creating fully up to date credentials file

### ISSUE THREAD

**Issue by jpeeler** [CircleCI-Public/aws-cli-orb#198]
I'm using a local runner, so the environment is not created from scratch for every job. The problem I'm experiencing is that when short lived credentials are utilized (aws_session_token) followed by a job using normal credentials, the existing session token is not removed from the configuration file. I would think it's okay to empty the credentials file before repopulating, but maybe a safer alternative is a move operation to a backup file? Or perhaps at a minimum the orb should warn that the file has not been fully updated.

https://github.com/CircleCI-Public/aws-cli-orb/blob/8cb46da8bda6cd3ee40487dd3bdf8e02568609d4/src/scripts/configure.sh#L26-L29

Sounds closely related to https://github.com/CircleCI-Public/aws-cli-orb/issues/139.

In the meantime, I suppose I'll ensure to remove the credentials file manually after a job is completed.

**Comment by marboledacci** [comment]
The version 5.1.1 should fix this. Just one thing to consider, when you are using multiple setups, the first one must set `set_aws_env_vars` to false https://github.com/CircleCI-Public/aws-cli-orb/blob/51996a179f32dc0102b20491eb83ece96109d3b0/src/commands/setup.yml#L99

Otherwise the OIDC will write the keys into the environment, and these will take precedence over the ones you pass directly to the command.
