### ISSUE TITLE
Handle `which` not installed

### ISSUE THREAD

**Issue by brandon-leapyear** [CircleCI-Public/aws-cli-orb#77]
Use `type` instead, which is a bash built-in

**Comment by KyleTryon** [comment]
Hey @brandon-leapyear,

Thanks for sending this in. I was not aware of the `type` command! Thank you for showing it to me.

I am having a little bit of a difficult type researching it but I wanted to share what I found. From my findings it seems that maybe `command -v` is a better generalized command. But I would like to hear more from you and your use-case.

Apologies if we are too late here, I realize this issue is quite old now.

https://en.wikipedia.org/wiki/Type_(Unix)

> The type command was a [shell builtin](https://en.wikipedia.org/wiki/Shell_builtin) for [Bourne shell](https://en.wikipedia.org/wiki/Bourne_shell) that was introduced in [AT&T's System V Release 2 (SVR2)](https://en.wikipedia.org/wiki/SVR2) in 1984,[[1]](https://en.wikipedia.org/wiki/Type_(Unix)#cite_note-1) and continues to be included in many other POSIX-compatible shells such as [Bash](https://en.wikipedia.org/wiki/Bash_(Unix_shell)). However, type is not part of the [POSIX standard](https://en.wikipedia.org/wiki/POSIX). With a POSIX shell, similar behavior is retrieved with
>```
> command -V name
> ```

https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then

> The status nowadays is that type and command -v are ubiquitous in all the Bourne-like shells

Here is an interesting point in your favor for POSIX compliant system

> POSIX requires that all shell builtins (like command) be also available as external commands, but unfortunately, that's not the case for command on many systems. For instance, it's rare to find a command command on Linux based operating systems while most of them have a which command (though different ones with different options and behaviors).

Would love to better understand the issues you are facing.

**Comment by brandon-leapyear** [comment]
I don't remember the exact situation, but I believe type or command would
both work for us.

**Comment by brivu** [comment]
This was resolved with PR #98
